USE gharpata;

ALTER TABLE users 
ADD COLUMN IF NOT EXISTS suspendedUntil TIMESTAMP NULL DEFAULT NULL;

-- Verification
SELECT COLUMN_NAME, DATA_TYPE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_SCHEMA = 'gharpata' AND TABLE_NAME = 'users' AND COLUMN_NAME = 'suspendedUntil';
